### ISSUE TITLE
Gmail.js API List

### ISSUE THREAD

**Issue by pranmar123** [pranmar123/AntiPhish#14]
- Look at the gmail.js docs and come up with a  list of API calls that our programs need to make in order to get the following:
    - The email body text
    - The sender's email and name
    - If there is no body text and there is only an image in the body, then get the link of that image.

**Comment by d-air1** [comment]
I believe I have identified the most comon api calls that we would use in order to get the contents of current and future emails.
The list is as follows:
gmail.dom**.header()**
gmail.dom**.email_contents()**
gmail.dom**.email_body()**
gmail.dom**.inbox_content()**
gmail.dom**.email_subject()**
gmail.get.user_email()
get.current_page()
get.email_subject()
get.unread_emails()

**Comment by d-air1** [comment]
Any reason to reopen this.

**Comment by d-air1** [comment]
?

**Comment by pranmar123** [comment]
@Dashon1 Re-opened this so I can create a wiki page that contains the information you provided.

**Comment by d-air1** [comment]
Alright cool

**Comment by pranmar123** [comment]
Investigation results noted on: https://github.com/pranmar123/AntiPhish/wiki/Plugin-Investigation
