### ISSUE TITLE
WebAccessibleResources Problem

### ISSUE THREAD

**Issue by pranmar123** [pranmar123/AntiPhish#17]
Problem: Gmail.js API is not loading before chrome loads Gmail.

- Look into adding WebAccessibleResources
- Goal is to have our script load before Chrome loads Gmail.

**Comment by d-air1** [comment]
I believe I've solved this with the recent pull request. Take a look and test it when you can. For now I'll close the issue. Reopen it if it doesn't work for you.

In order to test:
after merging the changes from this pull request
go to your gmail
open the dev tools console 
type the following command:
gmail.get.user_email();

if it returns your email, everything is working properly
