### ISSUE TITLE
Create boilerplate code from Extensionizr

### ISSUE THREAD

**Issue by pranmar123** [pranmar123/AntiPhish#6]
* Research and determine the appropriate settings needed for our extension
* Create the boilerplate code from Exensionizr 
* Integrate that code into our codebase

 https://extensionizr.com/!#{%22modules%22:[%22hidden-mode%22,%22with-bg%22,%22with-persistent-bg%22,%22no-options%22,%22no-override%22],%22boolean_perms%22:[],%22match_ptrns%22:[]}

**Comment by d-air1** [comment]
I've created the code using the potential permissions and features I thought we would need for our project. It can of course be tweaked later if I missed anything. Spent a lot of unnecessary time fiddling around with the website. It wouldn't work in firefox. I'll tweak it a bit more and prepare it to be integrated into our code base.

**Comment by d-air1** [comment]
The code has been integrated and can be downloaded and installed by the rest of the group. I explained the current problems as well as what all functionality it has currently in my last commit message. Give it a try if you like. Otherwise we can discuss things at the next meeting. I'll close this issue since the objective has been accomplished.

**Comment by pranmar123** [comment]
@Dashon1 Re-opened this issue because I want to clean up the codebase. Are the files in the basics folder (other than README.md and PULL_REQUEST_TEMPLATE) needed anymore?

**Comment by d-air1** [comment]
No we don't need them. I just forgot to delete them.

**Comment by d-air1** [comment]
Currently the options we chose are to have the following:
page action
background will be in javascript
no options page since we are only giving a result and I couldn't think of anything to configure
tab override just in case
inject javascript because of a constraint in gmail.js
added jquery since it is the only dependency of gmail.js
url permissions for gmail.com

My bad for taking so long to add the configuration options.
